ARG base_image=registry.access.redhat.com/ubi8/ubi-minimal:8.1
FROM ${base_image}
MAINTAINER Tom Manville<tom@kasten.io>
RUN microdnf install git && \
    microdnf clean all

ADD ARG_SOURCE_BIN /ARG_BIN
ENTRYPOINT ["/ARG_BIN"]
