ARG base_image=default
FROM registry.access.redhat.com/ubi9/ubi-minimal:9.8@sha256:7b8e25a1b56ca4d00219198f3b5b51a3e1693a5c4f5369c5e190d7d6cb3f980e AS default

FROM ${base_image}
ARG kanister_version

LABEL name=ARG_BIN \
      vendor="Kanister" \
      version="${kanister_version}" \
      release="${kanister_version}" \
      summary="Microservice for application-specific data management" \
      maintainer="Kanister maintainers<kanister.maintainers@veeam.com>" \
      description="Frameworks and utilities for application-specific data management, has updated openssl-libs."

RUN microdnf -y update openssl-libs cyrus-sasl-lib && \
    microdnf -y install git && \
    microdnf clean all

COPY licenses /licenses/licenses

ADD ARG_SOURCE_BIN /ARG_BIN
ENTRYPOINT ["/ARG_BIN"]
