ARG base_image=default
FROM registry.access.redhat.com/ubi9/ubi-minimal:9.8@sha256:7c372902c8d211db2d25c8277ba534a73b92742a334874dced829a63b0f21221 AS default

FROM ${base_image}
ARG kanister_version

LABEL name=ARG_BIN \
      vendor="Kanister" \
      version="${kanister_version}" \
      release="${kanister_version}" \
      summary="Microservice for application-specific data management" \
      maintainer="Kanister maintainers<kanister.maintainers@veeam.com>" \
      description="Frameworks and utilities for application-specific data management, has updated openssl-libs."

RUN microdnf -y update openssl-libs cyrus-sasl-lib && \
    microdnf -y install git && \
    microdnf clean all

COPY licenses /licenses/licenses

ADD ARG_SOURCE_BIN /ARG_BIN
ENTRYPOINT ["/ARG_BIN"]
