/*
Copyright 2025 by contributors to the Kanister project.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	crv1alpha1 "github.com/kanisterio/kanister/pkg/apis/cr/v1alpha1"
	applyconfigurationcrv1alpha1 "github.com/kanisterio/kanister/pkg/client/applyconfiguration/cr/v1alpha1"
	scheme "github.com/kanisterio/kanister/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// ActionSetsGetter has a method to return a ActionSetInterface.
// A group's client should implement this interface.
type ActionSetsGetter interface {
	ActionSets(namespace string) ActionSetInterface
}

// ActionSetInterface has methods to work with ActionSet resources.
type ActionSetInterface interface {
	Create(ctx context.Context, actionSet *crv1alpha1.ActionSet, opts v1.CreateOptions) (*crv1alpha1.ActionSet, error)
	Update(ctx context.Context, actionSet *crv1alpha1.ActionSet, opts v1.UpdateOptions) (*crv1alpha1.ActionSet, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*crv1alpha1.ActionSet, error)
	List(ctx context.Context, opts v1.ListOptions) (*crv1alpha1.ActionSetList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *crv1alpha1.ActionSet, err error)
	Apply(ctx context.Context, actionSet *applyconfigurationcrv1alpha1.ActionSetApplyConfiguration, opts v1.ApplyOptions) (result *crv1alpha1.ActionSet, err error)
	ActionSetExpansion
}

// actionSets implements ActionSetInterface
type actionSets struct {
	*gentype.ClientWithListAndApply[*crv1alpha1.ActionSet, *crv1alpha1.ActionSetList, *applyconfigurationcrv1alpha1.ActionSetApplyConfiguration]
}

// newActionSets returns a ActionSets
func newActionSets(c *CrV1alpha1Client, namespace string) *actionSets {
	return &actionSets{
		gentype.NewClientWithListAndApply[*crv1alpha1.ActionSet, *crv1alpha1.ActionSetList, *applyconfigurationcrv1alpha1.ActionSetApplyConfiguration](
			"actionsets",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *crv1alpha1.ActionSet { return &crv1alpha1.ActionSet{} },
			func() *crv1alpha1.ActionSetList { return &crv1alpha1.ActionSetList{} },
		),
	}
}
