/*
Copyright 2025 by contributors to the Kanister project.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	crv1alpha1 "github.com/kanisterio/kanister/pkg/apis/cr/v1alpha1"
	applyconfigurationcrv1alpha1 "github.com/kanisterio/kanister/pkg/client/applyconfiguration/cr/v1alpha1"
	scheme "github.com/kanisterio/kanister/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// BlueprintsGetter has a method to return a BlueprintInterface.
// A group's client should implement this interface.
type BlueprintsGetter interface {
	Blueprints(namespace string) BlueprintInterface
}

// BlueprintInterface has methods to work with Blueprint resources.
type BlueprintInterface interface {
	Create(ctx context.Context, blueprint *crv1alpha1.Blueprint, opts v1.CreateOptions) (*crv1alpha1.Blueprint, error)
	Update(ctx context.Context, blueprint *crv1alpha1.Blueprint, opts v1.UpdateOptions) (*crv1alpha1.Blueprint, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*crv1alpha1.Blueprint, error)
	List(ctx context.Context, opts v1.ListOptions) (*crv1alpha1.BlueprintList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *crv1alpha1.Blueprint, err error)
	Apply(ctx context.Context, blueprint *applyconfigurationcrv1alpha1.BlueprintApplyConfiguration, opts v1.ApplyOptions) (result *crv1alpha1.Blueprint, err error)
	BlueprintExpansion
}

// blueprints implements BlueprintInterface
type blueprints struct {
	*gentype.ClientWithListAndApply[*crv1alpha1.Blueprint, *crv1alpha1.BlueprintList, *applyconfigurationcrv1alpha1.BlueprintApplyConfiguration]
}

// newBlueprints returns a Blueprints
func newBlueprints(c *CrV1alpha1Client, namespace string) *blueprints {
	return &blueprints{
		gentype.NewClientWithListAndApply[*crv1alpha1.Blueprint, *crv1alpha1.BlueprintList, *applyconfigurationcrv1alpha1.BlueprintApplyConfiguration](
			"blueprints",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *crv1alpha1.Blueprint { return &crv1alpha1.Blueprint{} },
			func() *crv1alpha1.BlueprintList { return &crv1alpha1.BlueprintList{} },
		),
	}
}
