// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

type ActionSetExpansion interface{}

type BlueprintExpansion interface{}

type ProfileExpansion interface{}

type RepositoryServerExpansion interface{}
