/*
Copyright 2024 The Kanister Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	json "encoding/json"
	"fmt"
	"time"

	v1alpha1 "github.com/kanisterio/kanister/pkg/apis/cr/v1alpha1"
	crv1alpha1 "github.com/kanisterio/kanister/pkg/client/applyconfiguration/cr/v1alpha1"
	scheme "github.com/kanisterio/kanister/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// RepositoryServersGetter has a method to return a RepositoryServerInterface.
// A group's client should implement this interface.
type RepositoryServersGetter interface {
	RepositoryServers(namespace string) RepositoryServerInterface
}

// RepositoryServerInterface has methods to work with RepositoryServer resources.
type RepositoryServerInterface interface {
	Create(ctx context.Context, repositoryServer *v1alpha1.RepositoryServer, opts v1.CreateOptions) (*v1alpha1.RepositoryServer, error)
	Update(ctx context.Context, repositoryServer *v1alpha1.RepositoryServer, opts v1.UpdateOptions) (*v1alpha1.RepositoryServer, error)
	UpdateStatus(ctx context.Context, repositoryServer *v1alpha1.RepositoryServer, opts v1.UpdateOptions) (*v1alpha1.RepositoryServer, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.RepositoryServer, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.RepositoryServerList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.RepositoryServer, err error)
	Apply(ctx context.Context, repositoryServer *crv1alpha1.RepositoryServerApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.RepositoryServer, err error)
	ApplyStatus(ctx context.Context, repositoryServer *crv1alpha1.RepositoryServerApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.RepositoryServer, err error)
	RepositoryServerExpansion
}

// repositoryServers implements RepositoryServerInterface
type repositoryServers struct {
	client rest.Interface
	ns     string
}

// newRepositoryServers returns a RepositoryServers
func newRepositoryServers(c *CrV1alpha1Client, namespace string) *repositoryServers {
	return &repositoryServers{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the repositoryServer, and returns the corresponding repositoryServer object, and an error if there is any.
func (c *repositoryServers) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.RepositoryServer, err error) {
	result = &v1alpha1.RepositoryServer{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("repositoryservers").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of RepositoryServers that match those selectors.
func (c *repositoryServers) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.RepositoryServerList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.RepositoryServerList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("repositoryservers").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested repositoryServers.
func (c *repositoryServers) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("repositoryservers").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a repositoryServer and creates it.  Returns the server's representation of the repositoryServer, and an error, if there is any.
func (c *repositoryServers) Create(ctx context.Context, repositoryServer *v1alpha1.RepositoryServer, opts v1.CreateOptions) (result *v1alpha1.RepositoryServer, err error) {
	result = &v1alpha1.RepositoryServer{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("repositoryservers").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(repositoryServer).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a repositoryServer and updates it. Returns the server's representation of the repositoryServer, and an error, if there is any.
func (c *repositoryServers) Update(ctx context.Context, repositoryServer *v1alpha1.RepositoryServer, opts v1.UpdateOptions) (result *v1alpha1.RepositoryServer, err error) {
	result = &v1alpha1.RepositoryServer{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("repositoryservers").
		Name(repositoryServer.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(repositoryServer).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *repositoryServers) UpdateStatus(ctx context.Context, repositoryServer *v1alpha1.RepositoryServer, opts v1.UpdateOptions) (result *v1alpha1.RepositoryServer, err error) {
	result = &v1alpha1.RepositoryServer{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("repositoryservers").
		Name(repositoryServer.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(repositoryServer).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the repositoryServer and deletes it. Returns an error if one occurs.
func (c *repositoryServers) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("repositoryservers").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *repositoryServers) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("repositoryservers").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched repositoryServer.
func (c *repositoryServers) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.RepositoryServer, err error) {
	result = &v1alpha1.RepositoryServer{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("repositoryservers").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}

// Apply takes the given apply declarative configuration, applies it and returns the applied repositoryServer.
func (c *repositoryServers) Apply(ctx context.Context, repositoryServer *crv1alpha1.RepositoryServerApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.RepositoryServer, err error) {
	if repositoryServer == nil {
		return nil, fmt.Errorf("repositoryServer provided to Apply must not be nil")
	}
	patchOpts := opts.ToPatchOptions()
	data, err := json.Marshal(repositoryServer)
	if err != nil {
		return nil, err
	}
	name := repositoryServer.Name
	if name == nil {
		return nil, fmt.Errorf("repositoryServer.Name must be provided to Apply")
	}
	result = &v1alpha1.RepositoryServer{}
	err = c.client.Patch(types.ApplyPatchType).
		Namespace(c.ns).
		Resource("repositoryservers").
		Name(*name).
		VersionedParams(&patchOpts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}

// ApplyStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
func (c *repositoryServers) ApplyStatus(ctx context.Context, repositoryServer *crv1alpha1.RepositoryServerApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.RepositoryServer, err error) {
	if repositoryServer == nil {
		return nil, fmt.Errorf("repositoryServer provided to Apply must not be nil")
	}
	patchOpts := opts.ToPatchOptions()
	data, err := json.Marshal(repositoryServer)
	if err != nil {
		return nil, err
	}

	name := repositoryServer.Name
	if name == nil {
		return nil, fmt.Errorf("repositoryServer.Name must be provided to Apply")
	}

	result = &v1alpha1.RepositoryServer{}
	err = c.client.Patch(types.ApplyPatchType).
		Namespace(c.ns).
		Resource("repositoryservers").
		Name(*name).
		SubResource("status").
		VersionedParams(&patchOpts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
