/*
Copyright 2025 by contributors to the Kanister project.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	crv1alpha1 "github.com/kanisterio/kanister/pkg/apis/cr/v1alpha1"
	applyconfigurationcrv1alpha1 "github.com/kanisterio/kanister/pkg/client/applyconfiguration/cr/v1alpha1"
	scheme "github.com/kanisterio/kanister/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// RepositoryServersGetter has a method to return a RepositoryServerInterface.
// A group's client should implement this interface.
type RepositoryServersGetter interface {
	RepositoryServers(namespace string) RepositoryServerInterface
}

// RepositoryServerInterface has methods to work with RepositoryServer resources.
type RepositoryServerInterface interface {
	Create(ctx context.Context, repositoryServer *crv1alpha1.RepositoryServer, opts v1.CreateOptions) (*crv1alpha1.RepositoryServer, error)
	Update(ctx context.Context, repositoryServer *crv1alpha1.RepositoryServer, opts v1.UpdateOptions) (*crv1alpha1.RepositoryServer, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, repositoryServer *crv1alpha1.RepositoryServer, opts v1.UpdateOptions) (*crv1alpha1.RepositoryServer, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*crv1alpha1.RepositoryServer, error)
	List(ctx context.Context, opts v1.ListOptions) (*crv1alpha1.RepositoryServerList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *crv1alpha1.RepositoryServer, err error)
	Apply(ctx context.Context, repositoryServer *applyconfigurationcrv1alpha1.RepositoryServerApplyConfiguration, opts v1.ApplyOptions) (result *crv1alpha1.RepositoryServer, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, repositoryServer *applyconfigurationcrv1alpha1.RepositoryServerApplyConfiguration, opts v1.ApplyOptions) (result *crv1alpha1.RepositoryServer, err error)
	RepositoryServerExpansion
}

// repositoryServers implements RepositoryServerInterface
type repositoryServers struct {
	*gentype.ClientWithListAndApply[*crv1alpha1.RepositoryServer, *crv1alpha1.RepositoryServerList, *applyconfigurationcrv1alpha1.RepositoryServerApplyConfiguration]
}

// newRepositoryServers returns a RepositoryServers
func newRepositoryServers(c *CrV1alpha1Client, namespace string) *repositoryServers {
	return &repositoryServers{
		gentype.NewClientWithListAndApply[*crv1alpha1.RepositoryServer, *crv1alpha1.RepositoryServerList, *applyconfigurationcrv1alpha1.RepositoryServerApplyConfiguration](
			"repositoryservers",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *crv1alpha1.RepositoryServer { return &crv1alpha1.RepositoryServer{} },
			func() *crv1alpha1.RepositoryServerList { return &crv1alpha1.RepositoryServerList{} },
		),
	}
}
