/*
Copyright 2025 by contributors to the Kanister project.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/kanisterio/kanister/pkg/apis/cr/v1alpha1"
	crv1alpha1 "github.com/kanisterio/kanister/pkg/client/applyconfiguration/cr/v1alpha1"
	typedcrv1alpha1 "github.com/kanisterio/kanister/pkg/client/clientset/versioned/typed/cr/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeBlueprints implements BlueprintInterface
type fakeBlueprints struct {
	*gentype.FakeClientWithListAndApply[*v1alpha1.Blueprint, *v1alpha1.BlueprintList, *crv1alpha1.BlueprintApplyConfiguration]
	Fake *FakeCrV1alpha1
}

func newFakeBlueprints(fake *FakeCrV1alpha1, namespace string) typedcrv1alpha1.BlueprintInterface {
	return &fakeBlueprints{
		gentype.NewFakeClientWithListAndApply[*v1alpha1.Blueprint, *v1alpha1.BlueprintList, *crv1alpha1.BlueprintApplyConfiguration](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("blueprints"),
			v1alpha1.SchemeGroupVersion.WithKind("Blueprint"),
			func() *v1alpha1.Blueprint { return &v1alpha1.Blueprint{} },
			func() *v1alpha1.BlueprintList { return &v1alpha1.BlueprintList{} },
			func(dst, src *v1alpha1.BlueprintList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.BlueprintList) []*v1alpha1.Blueprint { return gentype.ToPointerSlice(list.Items) },
			func(list *v1alpha1.BlueprintList, items []*v1alpha1.Blueprint) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
