FROM foundationdb/foundationdb:7.4.5

LABEL maintainer="Kanister maintainers<kanister.maintainers@veeam.com>"

# Install kando 
RUN curl https://raw.githubusercontent.com/kanisterio/kanister/master/scripts/get.sh | bash
