FROM foundationdb/foundationdb:6.3.22

MAINTAINER "Kanister maintainers <kanister.maintainers@veeam.com>"

# Install kando 
RUN curl https://raw.githubusercontent.com/kanisterio/kanister/master/scripts/get.sh | bash
