/*
Copyright 2025 by contributors to the Kanister project.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	crv1alpha1 "github.com/kanisterio/kanister/pkg/apis/cr/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// BlueprintLister helps list Blueprints.
// All objects returned here must be treated as read-only.
type BlueprintLister interface {
	// List lists all Blueprints in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*crv1alpha1.Blueprint, err error)
	// Blueprints returns an object that can list and get Blueprints.
	Blueprints(namespace string) BlueprintNamespaceLister
	BlueprintListerExpansion
}

// blueprintLister implements the BlueprintLister interface.
type blueprintLister struct {
	listers.ResourceIndexer[*crv1alpha1.Blueprint]
}

// NewBlueprintLister returns a new BlueprintLister.
func NewBlueprintLister(indexer cache.Indexer) BlueprintLister {
	return &blueprintLister{listers.New[*crv1alpha1.Blueprint](indexer, crv1alpha1.Resource("blueprint"))}
}

// Blueprints returns an object that can list and get Blueprints.
func (s *blueprintLister) Blueprints(namespace string) BlueprintNamespaceLister {
	return blueprintNamespaceLister{listers.NewNamespaced[*crv1alpha1.Blueprint](s.ResourceIndexer, namespace)}
}

// BlueprintNamespaceLister helps list and get Blueprints.
// All objects returned here must be treated as read-only.
type BlueprintNamespaceLister interface {
	// List lists all Blueprints in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*crv1alpha1.Blueprint, err error)
	// Get retrieves the Blueprint from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*crv1alpha1.Blueprint, error)
	BlueprintNamespaceListerExpansion
}

// blueprintNamespaceLister implements the BlueprintNamespaceLister
// interface.
type blueprintNamespaceLister struct {
	listers.ResourceIndexer[*crv1alpha1.Blueprint]
}
