// This file was automatically generated by lister-gen

package v1alpha1

// ActionSetListerExpansion allows custom methods to be added to
// ActionSetLister.
type ActionSetListerExpansion interface{}

// ActionSetNamespaceListerExpansion allows custom methods to be added to
// ActionSetNamespaceLister.
type ActionSetNamespaceListerExpansion interface{}

// BlueprintListerExpansion allows custom methods to be added to
// BlueprintLister.
type BlueprintListerExpansion interface{}

// BlueprintNamespaceListerExpansion allows custom methods to be added to
// BlueprintNamespaceLister.
type BlueprintNamespaceListerExpansion interface{}

// ProfileListerExpansion allows custom methods to be added to
// ProfileLister.
type ProfileListerExpansion interface{}

// ProfileNamespaceListerExpansion allows custom methods to be added to
// ProfileNamespaceLister.
type ProfileNamespaceListerExpansion interface{}
