/*
Copyright 2024 The Kanister Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// ActionSetListerExpansion allows custom methods to be added to
// ActionSetLister.
type ActionSetListerExpansion interface{}

// ActionSetNamespaceListerExpansion allows custom methods to be added to
// ActionSetNamespaceLister.
type ActionSetNamespaceListerExpansion interface{}

// BlueprintListerExpansion allows custom methods to be added to
// BlueprintLister.
type BlueprintListerExpansion interface{}

// BlueprintNamespaceListerExpansion allows custom methods to be added to
// BlueprintNamespaceLister.
type BlueprintNamespaceListerExpansion interface{}

// ProfileListerExpansion allows custom methods to be added to
// ProfileLister.
type ProfileListerExpansion interface{}

// ProfileNamespaceListerExpansion allows custom methods to be added to
// ProfileNamespaceLister.
type ProfileNamespaceListerExpansion interface{}

// RepositoryServerListerExpansion allows custom methods to be added to
// RepositoryServerLister.
type RepositoryServerListerExpansion interface{}

// RepositoryServerNamespaceListerExpansion allows custom methods to be added to
// RepositoryServerNamespaceLister.
type RepositoryServerNamespaceListerExpansion interface{}
