// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: pkg/kanx/kanx.proto

package kanx

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ProcessService_CreateProcess_FullMethodName = "/kanx.ProcessService/CreateProcess"
	ProcessService_GetProcess_FullMethodName    = "/kanx.ProcessService/GetProcess"
	ProcessService_ListProcesses_FullMethodName = "/kanx.ProcessService/ListProcesses"
	ProcessService_SignalProcess_FullMethodName = "/kanx.ProcessService/SignalProcess"
	ProcessService_Stdout_FullMethodName        = "/kanx.ProcessService/Stdout"
	ProcessService_Stderr_FullMethodName        = "/kanx.ProcessService/Stderr"
)

// ProcessServiceClient is the client API for ProcessService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProcessServiceClient interface {
	CreateProcess(ctx context.Context, in *CreateProcessRequest, opts ...grpc.CallOption) (*Process, error)
	GetProcess(ctx context.Context, in *ProcessPidRequest, opts ...grpc.CallOption) (*Process, error)
	ListProcesses(ctx context.Context, in *ListProcessesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Process], error)
	SignalProcess(ctx context.Context, in *SignalProcessRequest, opts ...grpc.CallOption) (*Process, error)
	Stdout(ctx context.Context, in *ProcessPidRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Output], error)
	Stderr(ctx context.Context, in *ProcessPidRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Output], error)
}

type processServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProcessServiceClient(cc grpc.ClientConnInterface) ProcessServiceClient {
	return &processServiceClient{cc}
}

func (c *processServiceClient) CreateProcess(ctx context.Context, in *CreateProcessRequest, opts ...grpc.CallOption) (*Process, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Process)
	err := c.cc.Invoke(ctx, ProcessService_CreateProcess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *processServiceClient) GetProcess(ctx context.Context, in *ProcessPidRequest, opts ...grpc.CallOption) (*Process, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Process)
	err := c.cc.Invoke(ctx, ProcessService_GetProcess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *processServiceClient) ListProcesses(ctx context.Context, in *ListProcessesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Process], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ProcessService_ServiceDesc.Streams[0], ProcessService_ListProcesses_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ListProcessesRequest, Process]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ProcessService_ListProcessesClient = grpc.ServerStreamingClient[Process]

func (c *processServiceClient) SignalProcess(ctx context.Context, in *SignalProcessRequest, opts ...grpc.CallOption) (*Process, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Process)
	err := c.cc.Invoke(ctx, ProcessService_SignalProcess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *processServiceClient) Stdout(ctx context.Context, in *ProcessPidRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Output], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ProcessService_ServiceDesc.Streams[1], ProcessService_Stdout_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ProcessPidRequest, Output]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ProcessService_StdoutClient = grpc.ServerStreamingClient[Output]

func (c *processServiceClient) Stderr(ctx context.Context, in *ProcessPidRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Output], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ProcessService_ServiceDesc.Streams[2], ProcessService_Stderr_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ProcessPidRequest, Output]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ProcessService_StderrClient = grpc.ServerStreamingClient[Output]

// ProcessServiceServer is the server API for ProcessService service.
// All implementations must embed UnimplementedProcessServiceServer
// for forward compatibility.
type ProcessServiceServer interface {
	CreateProcess(context.Context, *CreateProcessRequest) (*Process, error)
	GetProcess(context.Context, *ProcessPidRequest) (*Process, error)
	ListProcesses(*ListProcessesRequest, grpc.ServerStreamingServer[Process]) error
	SignalProcess(context.Context, *SignalProcessRequest) (*Process, error)
	Stdout(*ProcessPidRequest, grpc.ServerStreamingServer[Output]) error
	Stderr(*ProcessPidRequest, grpc.ServerStreamingServer[Output]) error
	mustEmbedUnimplementedProcessServiceServer()
}

// UnimplementedProcessServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProcessServiceServer struct{}

func (UnimplementedProcessServiceServer) CreateProcess(context.Context, *CreateProcessRequest) (*Process, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateProcess not implemented")
}
func (UnimplementedProcessServiceServer) GetProcess(context.Context, *ProcessPidRequest) (*Process, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProcess not implemented")
}
func (UnimplementedProcessServiceServer) ListProcesses(*ListProcessesRequest, grpc.ServerStreamingServer[Process]) error {
	return status.Errorf(codes.Unimplemented, "method ListProcesses not implemented")
}
func (UnimplementedProcessServiceServer) SignalProcess(context.Context, *SignalProcessRequest) (*Process, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignalProcess not implemented")
}
func (UnimplementedProcessServiceServer) Stdout(*ProcessPidRequest, grpc.ServerStreamingServer[Output]) error {
	return status.Errorf(codes.Unimplemented, "method Stdout not implemented")
}
func (UnimplementedProcessServiceServer) Stderr(*ProcessPidRequest, grpc.ServerStreamingServer[Output]) error {
	return status.Errorf(codes.Unimplemented, "method Stderr not implemented")
}
func (UnimplementedProcessServiceServer) mustEmbedUnimplementedProcessServiceServer() {}
func (UnimplementedProcessServiceServer) testEmbeddedByValue()                        {}

// UnsafeProcessServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProcessServiceServer will
// result in compilation errors.
type UnsafeProcessServiceServer interface {
	mustEmbedUnimplementedProcessServiceServer()
}

func RegisterProcessServiceServer(s grpc.ServiceRegistrar, srv ProcessServiceServer) {
	// If the following call pancis, it indicates UnimplementedProcessServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProcessService_ServiceDesc, srv)
}

func _ProcessService_CreateProcess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateProcessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProcessServiceServer).CreateProcess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProcessService_CreateProcess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProcessServiceServer).CreateProcess(ctx, req.(*CreateProcessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProcessService_GetProcess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProcessPidRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProcessServiceServer).GetProcess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProcessService_GetProcess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProcessServiceServer).GetProcess(ctx, req.(*ProcessPidRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProcessService_ListProcesses_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListProcessesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ProcessServiceServer).ListProcesses(m, &grpc.GenericServerStream[ListProcessesRequest, Process]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ProcessService_ListProcessesServer = grpc.ServerStreamingServer[Process]

func _ProcessService_SignalProcess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignalProcessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProcessServiceServer).SignalProcess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProcessService_SignalProcess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProcessServiceServer).SignalProcess(ctx, req.(*SignalProcessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProcessService_Stdout_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ProcessPidRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ProcessServiceServer).Stdout(m, &grpc.GenericServerStream[ProcessPidRequest, Output]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ProcessService_StdoutServer = grpc.ServerStreamingServer[Output]

func _ProcessService_Stderr_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ProcessPidRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ProcessServiceServer).Stderr(m, &grpc.GenericServerStream[ProcessPidRequest, Output]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ProcessService_StderrServer = grpc.ServerStreamingServer[Output]

// ProcessService_ServiceDesc is the grpc.ServiceDesc for ProcessService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProcessService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kanx.ProcessService",
	HandlerType: (*ProcessServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateProcess",
			Handler:    _ProcessService_CreateProcess_Handler,
		},
		{
			MethodName: "GetProcess",
			Handler:    _ProcessService_GetProcess_Handler,
		},
		{
			MethodName: "SignalProcess",
			Handler:    _ProcessService_SignalProcess_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListProcesses",
			Handler:       _ProcessService_ListProcesses_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Stdout",
			Handler:       _ProcessService_Stdout_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Stderr",
			Handler:       _ProcessService_Stderr_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "pkg/kanx/kanx.proto",
}
