/*
Copyright 2024 The Kanister Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/kanisterio/kanister/pkg/apis/cr/v1alpha1"
)

// LocationApplyConfiguration represents an declarative configuration of the Location type for use
// with apply.
type LocationApplyConfiguration struct {
	Type     *v1alpha1.LocationType `json:"type,omitempty"`
	Bucket   *string                `json:"bucket,omitempty"`
	Endpoint *string                `json:"endpoint,omitempty"`
	Prefix   *string                `json:"prefix,omitempty"`
	Region   *string                `json:"region,omitempty"`
}

// LocationApplyConfiguration constructs an declarative configuration of the Location type for use with
// apply.
func Location() *LocationApplyConfiguration {
	return &LocationApplyConfiguration{}
}

// WithType sets the Type field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Type field is set to the value of the last call.
func (b *LocationApplyConfiguration) WithType(value v1alpha1.LocationType) *LocationApplyConfiguration {
	b.Type = &value
	return b
}

// WithBucket sets the Bucket field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Bucket field is set to the value of the last call.
func (b *LocationApplyConfiguration) WithBucket(value string) *LocationApplyConfiguration {
	b.Bucket = &value
	return b
}

// WithEndpoint sets the Endpoint field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Endpoint field is set to the value of the last call.
func (b *LocationApplyConfiguration) WithEndpoint(value string) *LocationApplyConfiguration {
	b.Endpoint = &value
	return b
}

// WithPrefix sets the Prefix field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Prefix field is set to the value of the last call.
func (b *LocationApplyConfiguration) WithPrefix(value string) *LocationApplyConfiguration {
	b.Prefix = &value
	return b
}

// WithRegion sets the Region field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Region field is set to the value of the last call.
func (b *LocationApplyConfiguration) WithRegion(value string) *LocationApplyConfiguration {
	b.Region = &value
	return b
}
