/*
Copyright 2025 by contributors to the Kanister project.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// PhaseProgressApplyConfiguration represents a declarative configuration of the PhaseProgress type for use
// with apply.
//
// PhaseProgress represents the execution state of the phase.
type PhaseProgressApplyConfiguration struct {
	// ProgressPercent represents the execution progress in percentage.
	ProgressPercent *string `json:"progressPercent,omitempty"`
	// SizeDownloadedB represents the size of data downloaded in Bytes at a given time during phase execution.
	// This field will be empty for phases which do not involve data movement.
	SizeDownloadedB *int64 `json:"sizeDownloadedB,omitempty"`
	// SizeUploadedB represents the size of data uploaded in Bytes at a given time during phase execution.
	// This field will be empty for phases which do not involve data movement.
	SizeUploadedB *int64 `json:"sizeUploadedB,omitempty"`
	// EstimatedDownloadSizeB represents the total estimated size of data in Bytes
	// that will be downloaded during the phase execution.
	// This field will be empty for phases which do not involve data movement.
	EstimatedDownloadSizeB *int64 `json:"estimatedDownloadSizeB,omitempty"`
	// EstimatedUploadSizeB represents the total estimated size of data in Bytes
	// that will be uploaded during the phase execution.
	// This field will be empty for phases which do not involve data movement.
	EstimatedUploadSizeB *int64 `json:"estimatedUploadSizeB,omitempty"`
	// EstimatedTimeSeconds is the estimated time required in seconds to transfer the
	// remaining data estimated with EstimatedUploadSizeB/EstimatedDownloadSizeB.
	// This field will be empty for phases which do not involve data movement.
	EstimatedTimeSeconds *int64 `json:"estinatedTimeSeconds,omitempty"`
	// LastTransitionTime represents the last date time when the progress status
	// was received.
	LastTransitionTime *v1.Time `json:"lastTransitionTime,omitempty"`
}

// PhaseProgressApplyConfiguration constructs a declarative configuration of the PhaseProgress type for use with
// apply.
func PhaseProgress() *PhaseProgressApplyConfiguration {
	return &PhaseProgressApplyConfiguration{}
}

// WithProgressPercent sets the ProgressPercent field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ProgressPercent field is set to the value of the last call.
func (b *PhaseProgressApplyConfiguration) WithProgressPercent(value string) *PhaseProgressApplyConfiguration {
	b.ProgressPercent = &value
	return b
}

// WithSizeDownloadedB sets the SizeDownloadedB field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SizeDownloadedB field is set to the value of the last call.
func (b *PhaseProgressApplyConfiguration) WithSizeDownloadedB(value int64) *PhaseProgressApplyConfiguration {
	b.SizeDownloadedB = &value
	return b
}

// WithSizeUploadedB sets the SizeUploadedB field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SizeUploadedB field is set to the value of the last call.
func (b *PhaseProgressApplyConfiguration) WithSizeUploadedB(value int64) *PhaseProgressApplyConfiguration {
	b.SizeUploadedB = &value
	return b
}

// WithEstimatedDownloadSizeB sets the EstimatedDownloadSizeB field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the EstimatedDownloadSizeB field is set to the value of the last call.
func (b *PhaseProgressApplyConfiguration) WithEstimatedDownloadSizeB(value int64) *PhaseProgressApplyConfiguration {
	b.EstimatedDownloadSizeB = &value
	return b
}

// WithEstimatedUploadSizeB sets the EstimatedUploadSizeB field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the EstimatedUploadSizeB field is set to the value of the last call.
func (b *PhaseProgressApplyConfiguration) WithEstimatedUploadSizeB(value int64) *PhaseProgressApplyConfiguration {
	b.EstimatedUploadSizeB = &value
	return b
}

// WithEstimatedTimeSeconds sets the EstimatedTimeSeconds field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the EstimatedTimeSeconds field is set to the value of the last call.
func (b *PhaseProgressApplyConfiguration) WithEstimatedTimeSeconds(value int64) *PhaseProgressApplyConfiguration {
	b.EstimatedTimeSeconds = &value
	return b
}

// WithLastTransitionTime sets the LastTransitionTime field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LastTransitionTime field is set to the value of the last call.
func (b *PhaseProgressApplyConfiguration) WithLastTransitionTime(value v1.Time) *PhaseProgressApplyConfiguration {
	b.LastTransitionTime = &value
	return b
}
