/*
Copyright 2025 by contributors to the Kanister project.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// RepositoryServerSpecApplyConfiguration represents a declarative configuration of the RepositoryServerSpec type for use
// with apply.
//
// RepositoryServerSpec is the specification for the RepositoryServer
type RepositoryServerSpecApplyConfiguration struct {
	// Storage references the backend store where a repository already exists
	// and the credential necessary to connect to the backend store
	Storage *StorageApplyConfiguration `json:"storage,omitempty"`
	// Repository has the details required by the repository server
	// to connect to kopia repository
	Repository *RepositoryApplyConfiguration `json:"repository,omitempty"`
	// Server has the details of all the secrets required to start
	// the kopia repository server
	Server *ServerApplyConfiguration `json:"server,omitempty"`
}

// RepositoryServerSpecApplyConfiguration constructs a declarative configuration of the RepositoryServerSpec type for use with
// apply.
func RepositoryServerSpec() *RepositoryServerSpecApplyConfiguration {
	return &RepositoryServerSpecApplyConfiguration{}
}

// WithStorage sets the Storage field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Storage field is set to the value of the last call.
func (b *RepositoryServerSpecApplyConfiguration) WithStorage(value *StorageApplyConfiguration) *RepositoryServerSpecApplyConfiguration {
	b.Storage = value
	return b
}

// WithRepository sets the Repository field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Repository field is set to the value of the last call.
func (b *RepositoryServerSpecApplyConfiguration) WithRepository(value *RepositoryApplyConfiguration) *RepositoryServerSpecApplyConfiguration {
	b.Repository = value
	return b
}

// WithServer sets the Server field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Server field is set to the value of the last call.
func (b *RepositoryServerSpecApplyConfiguration) WithServer(value *ServerApplyConfiguration) *RepositoryServerSpecApplyConfiguration {
	b.Server = value
	return b
}
