package blockstorage

import (
	strfmt "github.com/go-openapi/strfmt"
)

// Volume A storage provider volume
type Volume struct {

	// Availability zone
	Az string

	// Time stamp when volume creation was initiated
	CreationTime TimeStamp

	// Volume is encrypted
	Encrypted bool

	// A unique identifier generated by the storage provider
	ID string

	// Volume IOPS, if specified for this volume
	Iops int64

	// The size of the volume, in GiB
	Size int64

	// tags
	Tags VolumeTags

	// Storage type for this volume
	Type Type

	// Volume type
	VolumeType string

	// Attributes specific to the provider
	Attributes map[string]string
}

// Snapshot of Volume
type Snapshot struct {

	// Time stamp when snapshot creation was initiated
	CreationTime TimeStamp

	// Snapshot is encrypted
	Encrypted bool

	// A unique identifier generated by the storage provider
	ID string

	// Snapshot availability region
	Region string

	// The size of the snapshot, in GiB
	Size int64

	// tags
	Tags SnapshotTags

	// Storage type of the source volume for this snapshot
	Type Type

	// volume
	Volume *Volume
}

// TimeStamp Time stamp for an event related to an object, for example when the object was created.
type TimeStamp strfmt.DateTime

// VolumeTags volume tags
type VolumeTags []*KeyValue

// SnapshotTags snapshot tags
type SnapshotTags []*KeyValue

// KeyValue String key-value pairs
type KeyValue struct {

	// Key or index name
	Key string

	// Value string
	Value string
}
