name: Publish docs
permissions:
  contents: read

on:
  workflow_call:
    inputs:
      release_tag:
        description: 'Existing git tag in the format x.x.x'
        required: true
        type: string
  workflow_dispatch:
     inputs:
      release_tag:
        description: 'Existing git tag in the format x.x.x'
        required: true
        type: string

jobs:
  build_docs:
    runs-on: ubuntu-latest
    env:
      RELEASE_TAG: ${{ inputs.release_tag }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ env.RELEASE_TAG }}
      - name: Setup pnpm
        uses: pnpm/action-setup@26f6d4f2c533a43e6b5da0b4a5dd983f98f7b49a # v4
        with:
          run_install: false
          package_json_file: docs/package.json
          version: 8
      - name: Setup Node
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v4
        with:
          node-version: 20
      - name: Setup Pages
        uses: actions/configure-pages@45bfe0192ca1faeb007ade9deae92b16b8254a0d # v6.0.0
      - name: Install dependencies
        run: pnpm install
        working-directory: ./docs
      - name: Build with VitePress
        run: |
          echo "{\"version\":\"${RELEASE_TAG}\"}" > ./.vitepress/version.json
          pnpm docs:build
        working-directory: ./docs
      - name: Upload artifact
        uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9 # v3
        with:
          path: docs/.vitepress/dist
          name: docs

  publish_docs:
    needs: build_docs

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128 #v5.0.0
        with:
          artifact_name: docs
